# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  -
    main: ./pkg/cli/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
archive:
  name_template: "semver_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
brew:
  github:
    owner: meinto
    name: git-semver
  commit_author:
    name: Tobias Meinhardt
    email: tobias.meinhardt89@gmail.com
  folder: formula
  dependencies:
    - git
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
