# This file was generated by GoReleaser. DO NOT EDIT.
class GitSemver < Formula
  desc ""
  homepage ""
  url "https://github.com/meinto/git-semver/releases/download/v4.1.8/git-semver_4.1.8_Darwin_x86_64.tar.gz"
  version "4.1.8"
  sha256 "e9d215884f46128c5c9ec1ef169ffb3b0c1100d018d90ec2b637d8cc97bccc91"
  
  depends_on "git"

  def install
    bin.install "git-semver"
  end
end
