# This file was generated by GoReleaser. DO NOT EDIT.
class GitSemver < Formula
  desc ""
  homepage ""
  url "https://github.com/meinto/git-semver/releases/download/v4.3.0/semver_4.3.0_darwin_x86_64.tar.gz"
  version "4.3.0"
  sha256 "cc49081633aa8d4ca397a8e6f6d570c92ef98da2f49148bea3f05f24be938977"
  
  depends_on "git"

  def install
    bin.install "git-semver"
  end
end
