# This file was generated by GoReleaser. DO NOT EDIT.
class Semver < Formula
  desc ""
  homepage ""
  url "https://github.com/meinto/git-semver/releases/download/v4.1.7/git-semver_4.1.7_Darwin_x86_64.tar.gz"
  version "4.1.7"
  sha256 "ee434c82cce746c9861820099b01d9b362ee5e9460c0d12c232781ffdc2c3255"
  
  depends_on "git"

  def install
    bin.install "git-semver"
  end
end
